language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - brew upgrade xctool
  
notifications:
  webhooks: http://progress.flatironschool.com/submissions

script: xctool -reporter json-stream -workspace tasksToday.xcworkspace -sdk iphonesimulator -destination "name=iPhone Retina (4-inch)" -scheme tasksToday build test
